require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - '**/spec/**/*'

RSpec/ExampleLength:
  Enabled: false
